package de.forsthaus.backend.model;

// Generated 18.10.2008 19:00:08 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Branche generated by hbm2java
 */
public class Branche implements java.io.Serializable {

	private static final long serialVersionUID = -8799762516266595746L;

	private long braId = Long.MIN_VALUE;
	private int version;
	private String braNr;
	private String braBezeichnung;
	private Set<Kunde> kundes = new HashSet<Kunde>(0);

	public boolean isNew() {
		return (getBraId() == Long.MIN_VALUE);
	}

	public Branche() {
	}

	public Branche(long braId, String braBezeichnung) {
		this.braId = braId;
		this.braBezeichnung = braBezeichnung;
	}

	public Branche(long braId, String braNr, String braBezeichnung, Set<Kunde> kundes) {
		this.braId = braId;
		this.braNr = braNr;
		this.braBezeichnung = braBezeichnung;
		this.kundes = kundes;
	}

	public long getBraId() {
		return this.braId;
	}

	public void setBraId(long braId) {
		this.braId = braId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getBraNr() {
		return this.braNr;
	}

	public void setBraNr(String braNr) {
		this.braNr = braNr;
	}

	public String getBraBezeichnung() {
		return this.braBezeichnung;
	}

	public void setBraBezeichnung(String braBezeichnung) {
		this.braBezeichnung = braBezeichnung;
	}

	public Set<Kunde> getKundes() {
		return this.kundes;
	}

	public void setKundes(Set<Kunde> kundes) {
		this.kundes = kundes;
	}

	@Override
	public int hashCode() {
		return Long.valueOf(getBraId()).hashCode();
	}

	public boolean equals(Branche branche) {
		return getBraId() == branche.getBraId();
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (obj instanceof Branche) {
			Branche branche = (Branche) obj;
			return equals(branche);
		}

		return false;
	}
}
