package de.forsthaus.backend.model;

// Generated 18.10.2008 19:00:08 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Kunde generated by hbm2java
 */
public class Kunde implements java.io.Serializable {

	private static final long serialVersionUID = -7921214349365225047L;

	private long kunId = Long.MIN_VALUE;
	private int version;
	private Branche branche;
	private String kunNr = "";
	private String kunMatchcode = "";
	private String kunName1 = "";
	private String kunName2 = "";
	private String kunOrt = "";
	private Boolean kunMahnsperre = false;
	private Set<Auftrag> auftrags = new HashSet<Auftrag>(0);

	public boolean isNew() {
		return (getKunId() == Long.MIN_VALUE);
	}

	public Kunde() {
	}

	public Kunde(long kunId) {
		this.kunId = kunId;
	}

	public Kunde(long kunId, Branche branche, String kunNr, String kunMatchcode, String kunName1, String kunName2, String kunOrt,
			Boolean kunMahnsperre, Set<Auftrag> auftrags) {
		this.kunId = kunId;
		this.branche = branche;
		this.kunNr = kunNr;
		this.kunMatchcode = kunMatchcode;
		this.kunName1 = kunName1;
		this.kunName2 = kunName2;
		this.kunOrt = kunOrt;
		this.kunMahnsperre = kunMahnsperre;
		this.auftrags = auftrags;
	}

	public long getKunId() {
		return this.kunId;
	}

	public void setKunId(long kunId) {
		this.kunId = kunId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public Branche getBranche() {
		return this.branche;
	}

	public void setBranche(Branche branche) {
		this.branche = branche;
	}

	public String getKunNr() {
		return this.kunNr;
	}

	public void setKunNr(String kunNr) {
		this.kunNr = kunNr;
	}

	public String getKunMatchcode() {
		return this.kunMatchcode;
	}

	public void setKunMatchcode(String kunMatchcode) {
		this.kunMatchcode = kunMatchcode;
	}

	public String getKunName1() {
		return this.kunName1;
	}

	public void setKunName1(String kunName1) {
		this.kunName1 = kunName1;
	}

	public String getKunName2() {
		return this.kunName2;
	}

	public void setKunName2(String kunName2) {
		this.kunName2 = kunName2;
	}

	public String getKunOrt() {
		return this.kunOrt;
	}

	public void setKunOrt(String kunOrt) {
		this.kunOrt = kunOrt;
	}

	public Boolean getKunMahnsperre() {
		return this.kunMahnsperre;
	}

	public void setKunMahnsperre(Boolean kunMahnsperre) {
		this.kunMahnsperre = kunMahnsperre;
	}

	public Set<Auftrag> getAuftrags() {
		return this.auftrags;
	}

	public void setAuftrags(Set<Auftrag> auftrags) {
		this.auftrags = auftrags;
	}

	@Override
	public int hashCode() {
		return Long.valueOf(getKunId()).hashCode();
	}

	public boolean equals(Kunde kunde) {
		return getKunId() == kunde.getKunId();
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (obj instanceof Kunde) {
			Kunde kunde = (Kunde) obj;
			return equals(kunde);
		}

		return false;
	}

}
