package de.forsthaus.backend.model;

// Generated 31.01.2009 22:31:49 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * SecRight generated by hbm2java
 */
public class SecRight implements java.io.Serializable {

	private static final long serialVersionUID = -1574628715506591010L;

	private long rigId = Long.MIN_VALUE;
	private int version;
	private Integer rigType;
	private String rigName;
	private Set<SecGroupright> secGrouprights = new HashSet<SecGroupright>(0);

	public boolean isNew() {
		return (getRigId() == Long.MIN_VALUE);
	}

	public SecRight() {
	}

	public SecRight(long rigId, String rigName) {
		this.rigId = rigId;
		this.rigName = rigName;
	}

	public SecRight(long rigId, Integer rigType, String rigName, Set<SecGroupright> secGrouprights) {
		this.rigId = rigId;
		this.rigType = rigType;
		this.rigName = rigName;
		this.secGrouprights = secGrouprights;
	}

	public long getRigId() {
		return this.rigId;
	}

	public void setRigId(long rigId) {
		this.rigId = rigId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public Integer getRigType() {
		return this.rigType;
	}

	public void setRigType(Integer rigType) {
		this.rigType = rigType;
	}

	public String getRigName() {
		return this.rigName;
	}

	public void setRigName(String rigName) {
		this.rigName = rigName;
	}

	public Set<SecGroupright> getSecGrouprights() {
		return this.secGrouprights;
	}

	public void setSecGrouprights(Set<SecGroupright> secGrouprights) {
		this.secGrouprights = secGrouprights;
	}

	@Override
	public int hashCode() {
		return Long.valueOf(getRigId()).hashCode();
	}

	public boolean equals(SecRight secRight) {
		return getRigId() == secRight.getRigId();
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (obj instanceof SecRight) {
			SecRight secRight = (SecRight) obj;
			return equals(secRight);
		}

		return false;
	}

}
