package de.forsthaus.backend.model;

// Generated 02.02.2009 14:17:37 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * SecRole generated by hbm2java
 */
public class SecRole implements java.io.Serializable {

	private static final long serialVersionUID = -7966378689254650569L;
	private long rolId = Long.MIN_VALUE;
	private int version;
	private String rolShortdescription;
	private String rolLongdescription;
	private Set<SecUserrole> secUserroles = new HashSet<SecUserrole>(0);
	private Set<SecRolegroup> secRolegroups = new HashSet<SecRolegroup>(0);

	public boolean isNew() {
		return (getRolId() == Long.MIN_VALUE);
	}

	public SecRole() {
	}

	public SecRole(long rolId, String rolShortdescription) {
		this.rolId = rolId;
		this.rolShortdescription = rolShortdescription;
	}

	public SecRole(long rolId, String rolShortdescription, String rolLongdescription, Set<SecUserrole> secUserroles,
			Set<SecRolegroup> secRolegroups) {
		this.rolId = rolId;
		this.rolShortdescription = rolShortdescription;
		this.rolLongdescription = rolLongdescription;
		this.secUserroles = secUserroles;
		this.secRolegroups = secRolegroups;
	}

	public long getRolId() {
		return this.rolId;
	}

	public void setRolId(long rolId) {
		this.rolId = rolId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getRolShortdescription() {
		return this.rolShortdescription;
	}

	public void setRolShortdescription(String rolShortdescription) {
		this.rolShortdescription = rolShortdescription;
	}

	public String getRolLongdescription() {
		return this.rolLongdescription;
	}

	public void setRolLongdescription(String rolLongdescription) {
		this.rolLongdescription = rolLongdescription;
	}

	public Set<SecUserrole> getSecUserroles() {
		return this.secUserroles;
	}

	public void setSecUserroles(Set<SecUserrole> secUserroles) {
		this.secUserroles = secUserroles;
	}

	public Set<SecRolegroup> getSecRolegroups() {
		return this.secRolegroups;
	}

	public void setSecRolegroups(Set<SecRolegroup> secRolegroups) {
		this.secRolegroups = secRolegroups;
	}

	@Override
	public int hashCode() {
		return Long.valueOf(getRolId()).hashCode();
	}

	public boolean equals(SecRole secRole) {
		return getRolId() == secRole.getRolId();
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (obj instanceof SecRole) {
			SecRole secRole = (SecRole) obj;
			return equals(secRole);
		}

		return false;
	}

}
