package de.forsthaus.backend.model;

// Generated 02.02.2009 14:17:37 by Hibernate Tools 3.2.2.GA

/**
 * SecRolegroup generated by hbm2java
 */
public class SecRolegroup implements java.io.Serializable {

	private static final long serialVersionUID = -8173065939240678650L;

	private long rlgId = Long.MIN_VALUE;
	private int version;
	private SecRole secRole;
	private SecGroup secGroup;

	public boolean isNew() {
		return (getRlgId() == Long.MIN_VALUE);
	}

	public SecRolegroup() {
	}

	public SecRolegroup(long rlgId) {
		this.rlgId = rlgId;
	}

	public SecRolegroup(long rlgId, SecRole secRole, SecGroup secGroup) {
		this.rlgId = rlgId;
		this.secRole = secRole;
		this.secGroup = secGroup;
	}

	public long getRlgId() {
		return this.rlgId;
	}

	public void setRlgId(long rlgId) {
		this.rlgId = rlgId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public SecRole getSecRole() {
		return this.secRole;
	}

	public void setSecRole(SecRole secRole) {
		this.secRole = secRole;
	}

	public SecGroup getSecGroup() {
		return this.secGroup;
	}

	public void setSecGroup(SecGroup secGroup) {
		this.secGroup = secGroup;
	}

	@Override
	public int hashCode() {
		return Long.valueOf(getRlgId()).hashCode();
	}

	public boolean equals(SecRolegroup secRolegroup) {
		return getRlgId() == secRolegroup.getRlgId();
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (obj instanceof SecRolegroup) {
			SecRolegroup secRolegroup = (SecRolegroup) obj;
			return equals(secRolegroup);
		}

		return false;
	}

}
