package de.forsthaus.backend.model;

// Generated 18.10.2008 19:00:08 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Auftrag generated by hbm2java
 */
public class Auftrag implements java.io.Serializable {

	private static final long serialVersionUID = 7394594643016754480L;

	private long aufId = Long.MIN_VALUE;
	private int version;
	private Kunde kunde;
	private String aufNr;
	private String aufBezeichnung;
	private Set<Auftragposition> auftragpositions = new HashSet<Auftragposition>(0);

	public boolean isNew() {
		return (getAufId() == Long.MIN_VALUE);
	}

	public Auftrag() {
	}

	public Auftrag(long aufId, Kunde kunde, String aufNr) {
		this.aufId = aufId;
		this.kunde = kunde;
		this.aufNr = aufNr;
	}

	public Auftrag(long aufId, Kunde kunde, String aufNr, String aufBezeichnung, Set<Auftragposition> auftragpositions) {
		this.aufId = aufId;
		this.kunde = kunde;
		this.aufNr = aufNr;
		this.aufBezeichnung = aufBezeichnung;
		this.auftragpositions = auftragpositions;
	}

	public long getAufId() {
		return this.aufId;
	}

	public void setAufId(long aufId) {
		this.aufId = aufId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public Kunde getKunde() {
		return this.kunde;
	}

	public void setKunde(Kunde kunde) {
		this.kunde = kunde;
	}

	public String getAufNr() {
		return this.aufNr;
	}

	public void setAufNr(String aufNr) {
		this.aufNr = aufNr;
	}

	public String getAufBezeichnung() {
		return this.aufBezeichnung;
	}

	public void setAufBezeichnung(String aufBezeichnung) {
		this.aufBezeichnung = aufBezeichnung;
	}

	public Set<Auftragposition> getAuftragpositions() {
		return this.auftragpositions;
	}

	public void setAuftragpositions(Set<Auftragposition> auftragpositions) {
		this.auftragpositions = auftragpositions;
	}

	@Override
	public int hashCode() {
		return Long.valueOf(getAufId()).hashCode();
	}

	public boolean equals(Auftrag auftrag) {
		return getAufId() == auftrag.getAufId();
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (obj instanceof Auftrag) {
			Auftrag auftrag = (Auftrag) obj;
			return equals(auftrag);
		}

		return false;
	}

}
