package de.forsthaus.backend.model;

// Generated 31.01.2009 22:31:49 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * SecGroup generated by hbm2java
 */
public class SecGroup implements java.io.Serializable {

	private static final long serialVersionUID = -3284638212223216652L;

	private long grpId = Long.MIN_VALUE;
	private int version;
	private String grpShortdescription;
	private String grpLongdescription;
	private Set<SecGroupright> secGrouprights = new HashSet<SecGroupright>(0);
	private Set<SecRolegroup> secRolegroups = new HashSet<SecRolegroup>(0);

	public boolean isNew() {
		return (getGrpId() == Long.MIN_VALUE);
	}

	public SecGroup() {
	}

	public SecGroup(long grpId, String grpShortdescription) {
		this.grpId = grpId;
		this.grpShortdescription = grpShortdescription;
	}

	public SecGroup(long grpId, String grpShortdescription, String grpLongdescription, Set<SecGroupright> secGrouprights,
			Set<SecRolegroup> secRolegroups) {
		this.grpId = grpId;
		this.grpShortdescription = grpShortdescription;
		this.grpLongdescription = grpLongdescription;
		this.secGrouprights = secGrouprights;
		this.secRolegroups = secRolegroups;
	}

	public long getGrpId() {
		return this.grpId;
	}

	public void setGrpId(long grpId) {
		this.grpId = grpId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getGrpShortdescription() {
		return this.grpShortdescription;
	}

	public void setGrpShortdescription(String grpShortdescription) {
		this.grpShortdescription = grpShortdescription;
	}

	public String getGrpLongdescription() {
		return this.grpLongdescription;
	}

	public void setGrpLongdescription(String grpLongdescription) {
		this.grpLongdescription = grpLongdescription;
	}

	public Set<SecGroupright> getSecGrouprights() {
		return this.secGrouprights;
	}

	public void setSecGrouprights(Set<SecGroupright> secGrouprights) {
		this.secGrouprights = secGrouprights;
	}

	public Set<SecRolegroup> getSecRolegroups() {
		return this.secRolegroups;
	}

	public void setSecRolegroups(Set<SecRolegroup> secRolegroups) {
		this.secRolegroups = secRolegroups;
	}

	@Override
	public int hashCode() {
		return Long.valueOf(getGrpId()).hashCode();
	}

	public boolean equals(SecGroup secGroup) {
		return getGrpId() == secGroup.getGrpId();
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (obj instanceof SecGroup) {
			SecGroup secGroup = (SecGroup) obj;
			return equals(secGroup);
		}

		return false;
	}

}
