package de.forsthaus.backend.model;

// Generated 31.01.2009 22:31:49 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * SecUser generated by hbm2java
 */
public class SecUser implements java.io.Serializable {

	private static final long serialVersionUID = -8443234918260997954L;

	private long usrId = Long.MIN_VALUE;
	private int version;
	private String usrLoginname;
	private String usrPassword;
	private String usrLastname;
	private String usrFirstname;
	private String usrEmail;
	private String usrLocale;
	private boolean usrEnabled;
	private boolean usrAccountnonexpired;
	private boolean usrCredentialsnonexpired;
	private boolean usrAccountnonlocked;
	private String usrToken;
	private Set<SecUserrole> secUserroles = new HashSet<SecUserrole>(0);

	public boolean isNew() {
		return (getUsrId() == Long.MIN_VALUE);
	}

	public SecUser() {
	}

	public SecUser(long usrId, String usrLoginname, String usrPassword, boolean usrEnabled, boolean usrAccountnonexpired,
			boolean usrCredentialsnonexpired, boolean usrAccountnonlocked) {
		this.usrId = usrId;
		this.usrLoginname = usrLoginname;
		this.usrPassword = usrPassword;
		this.usrEnabled = usrEnabled;
		this.usrAccountnonexpired = usrAccountnonexpired;
		this.usrCredentialsnonexpired = usrCredentialsnonexpired;
		this.usrAccountnonlocked = usrAccountnonlocked;
	}

	public SecUser(long usrId, String usrLoginname, String usrPassword, String usrLastname, String usrFirstname, String usrEmail,
			String usrLocale, boolean usrEnabled, boolean usrAccountnonexpired, boolean usrCredentialsnonexpired,
			boolean usrAccountnonlocked, Set<SecUserrole> secUserroles) {
		this.usrId = usrId;
		this.usrLoginname = usrLoginname;
		this.usrPassword = usrPassword;
		this.usrLastname = usrLastname;
		this.usrFirstname = usrFirstname;
		this.usrEmail = usrEmail;
		this.usrLocale = usrLocale;
		this.usrEnabled = usrEnabled;
		this.usrAccountnonexpired = usrAccountnonexpired;
		this.usrCredentialsnonexpired = usrCredentialsnonexpired;
		this.usrAccountnonlocked = usrAccountnonlocked;
		this.secUserroles = secUserroles;
	}

	public long getUsrId() {
		return this.usrId;
	}

	public void setUsrId(long usrId) {
		this.usrId = usrId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getUsrLoginname() {
		return this.usrLoginname;
	}

	public void setUsrLoginname(String usrLoginname) {
		this.usrLoginname = usrLoginname;
	}

	public String getUsrPassword() {
		return this.usrPassword;
	}

	public void setUsrPassword(String usrPassword) {
		this.usrPassword = usrPassword;
	}

	public String getUsrLastname() {
		return this.usrLastname;
	}

	public void setUsrLastname(String usrLastname) {
		this.usrLastname = usrLastname;
	}

	public String getUsrFirstname() {
		return this.usrFirstname;
	}

	public void setUsrFirstname(String usrFirstname) {
		this.usrFirstname = usrFirstname;
	}

	public String getUsrEmail() {
		return this.usrEmail;
	}

	public void setUsrEmail(String usrEmail) {
		this.usrEmail = usrEmail;
	}

	public String getUsrLocale() {
		return usrLocale;
	}

	public void setUsrLocale(String usrLocale) {
		this.usrLocale = usrLocale;
	}

	public boolean isUsrEnabled() {
		return this.usrEnabled;
	}

	public void setUsrEnabled(boolean usrEnabled) {
		this.usrEnabled = usrEnabled;
	}

	public boolean isUsrAccountnonexpired() {
		return this.usrAccountnonexpired;
	}

	public void setUsrAccountnonexpired(boolean usrAccountnonexpired) {
		this.usrAccountnonexpired = usrAccountnonexpired;
	}

	public boolean isUsrCredentialsnonexpired() {
		return this.usrCredentialsnonexpired;
	}

	public void setUsrCredentialsnonexpired(boolean usrCredentialsnonexpired) {
		this.usrCredentialsnonexpired = usrCredentialsnonexpired;
	}

	public boolean isUsrAccountnonlocked() {
		return this.usrAccountnonlocked;
	}

	public void setUsrAccountnonlocked(boolean usrAccountnonlocked) {
		this.usrAccountnonlocked = usrAccountnonlocked;
	}

	public String getUsrToken() {
		return this.usrToken;
	}

	public void setUsrToken(String usrToken) {
		this.usrToken = usrToken;
	}

	public Set<SecUserrole> getSecUserroles() {
		return this.secUserroles;
	}

	public void setSecUserroles(Set<SecUserrole> secUserroles) {
		this.secUserroles = secUserroles;
	}

	@Override
	public int hashCode() {
		return Long.valueOf(getUsrId()).hashCode();
	}

	public boolean equals(SecUser secUser) {
		return getUsrId() == secUser.getUsrId();
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (obj instanceof SecUser) {
			SecUser secUser = (SecUser) obj;
			return equals(secUser);
		}

		return false;
	}

}
